# Generated by Django 5.1.7 on 2025-03-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
