# Generated by Django 5.1.7 on 2025-04-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='comment',
            field=models.CharField(default='Thanks for your service', max_length=50),
            preserve_default=False,
        ),
    ]
