# Generated by Django 5.1.7 on 2025-03-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('status', models.BooleanField()),
                ('weight', models.FloatField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
