# Generated by Django 5.1.7 on 2025-03-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('weight', models.FloatField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
