# Generated by Django 5.1.7 on 2025-03-31 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='orders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.ordermodel'),
            preserve_default=False,
        ),
    ]
