# Generated by Django 5.1.7 on 2025-03-31 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0002_usermodel_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='orders.ordermodel'),
        ),
    ]
